// <auto-generated />
using CairoTransportation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CairoTransportation.Migrations
{
    [DbContext(typeof(TransportationDbContext))]
    [Migration("20260425123000_AddTrafficPeriodMultipliers")]
    partial class AddTrafficPeriodMultipliers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CairoTransportation.Models.TrafficPeriodMultiplier", b =>
                {
                    b.Property<string>("Period")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("period");

                    b.Property<double>("Multiplier")
                        .HasColumnType("REAL")
                        .HasColumnName("multiplier");

                    b.HasKey("Period");

                    b.ToTable("traffic_period_multipliers", null, t =>
                        {
                            t.HasCheckConstraint("chk_multiplier_positive", "multiplier > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
