// <auto-generated />
using CairoTransportation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CairoTransportation.Migrations
{
    [DbContext(typeof(TransportationDbContext))]
    [Migration("20260425130000_AddTrafficFlowPeriodForeignKey")]
    partial class AddTrafficFlowPeriodForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
