name: cairo-transportation

services:
  client:
    container_name: gcts-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://gcts-api.abosaleh.site
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - cloudflared-net
      - cairo-internal

  api:
    container_name: gcts-api
    build:
      context: ./Server/CairoTransportation
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    networks:
      - cloudflared-net
      - cairo-internal

networks:
  cloudflared-net:
    external: true

  cairo-internal:
    driver: bridge